/*
 * ADC_private.h
 *
 *  Created on: 17 Apr 2023
 *      Author: 20101
 */

#ifndef MCAL_ADC_ADC_PRIVATE_H_
#define MCAL_ADC_ADC_PRIVATE_H_

#define ADMUX_REG   	*(( VUchar8_t *)0x27)
#define ADCSRA_REG  	*(( VUchar8_t *)0x26)
#define ADCL_REG		*(( VUchar8_t *)0x24)
#define ADCH_REG		*(( VUchar8_t *)0x25)
#define SFIOR_REG		*(( VUchar8_t *)0x50)


typedef enum
{
	ADMUX_REG_MUX0_BIT = 0,
	ADMUX_REG_MUX1_BIT,
	ADMUX_REG_MUX2_BIT,
	ADMUX_REG_MUX3_BIT,
	ADMUX_REG_MUX4_BIT,
	ADMUX_REG_ADLAR_BIT,
	ADMUX_REG_REFS0_BIT,
	ADMUX_REG_REFS1_BIT
}ADMUX_REG_BITS_t;


typedef enum
{
	ADCSRA_REG_ADPS0_BIT = 0,
	ADCSRA_REG_ADPS1_BIT,
	ADCSRA_REG_ADPS2_BIT,
	ADCSRA_REG_ADIE_BIT,
	ADCSRA_REG_ADIF_BIT,
	ADCSRA_REG_ADATE_BIT,
	ADCSRA_REG_ADSC_BIT,
	ADCSRA_REG_ADEN_BIT
}ADCSRA_REG_BITS_t;


typedef enum
{
	SFIOR_REG_PSR10_BIT = 0,
	SFIOR_REG_PSR2_BIT,
	SFIOR_REG_PUD_BIT,
	SFIOR_REG_ACME_BIT,
	SFIOR_REG_RESERVED_BIT,
	SFIOR_REG_ADTS0_BIT,
	SFIOR_REG_ADTS1_BIT,
	SFIOR_REG_ADTS2_BIT
}SFIOR_REG_BITS_t;



#endif /* MCAL_ADC_ADC_PRIVATE_H_ */
